version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: cardb  # Tên cơ sở dữ liệu bạn muốn tạo
      POSTGRES_USER: postgres        # Tên người dùng
      POSTGRES_PASSWORD: 123         # Mật khẩu cho người dùng
    ports:
      - "5432:5432"
    networks:
      - dataoto-network
networks:
  dataoto-network:
